= Git

https://git-scm.com[Git] – это система контроля версий, используемая на подавляющем большинстве проектов в наши дни.
Знание Git (наряду с английским и навыками коммуникации) - ключ к успешной карьере инженера в IT (а не Java или фреймворки/библиотеки).

== Установка Git

Git, как и большинство инструментов разработки, доступен для Linux, Windows и macOS.
Отправная точка для установки Git – https://git-scm.com/downloads[страница "Downloads"] на официальном сайте.
Следуйте инструкциям на странице, соответствующей вашей операционной ситеме.

Git – в первую очередь консольная утилита.
Это означает, что он разработан для работы через текстовые команды, без графического интерфейса.
Тем не менее, Git поставляется с двумя графическими утилитами, `git gui` и `gitk`, а также существует https://git-scm.com/downloads/guis[множество] сторонних графических оболочек.
Также поддержка Git встроена во все популярные инструменты разработки – IntelliJ IDEA, Eclipse, VS Code и другие.

Я бы рекомендовал стараться использовать консольную утилиту `git` и "коробочные" `git gui` / `gitk`.
Но https://www.syntevo.com/smartgit[SmartGit] и https://www.gitkraken.com[GitKraken] довольно неплохи и бесплатны для персонального использования, а https://desktop.github.com[GitHub Desktop] поможет в работе с GitHub.
Можно попробовать и https://tortoisegit.org[TortoiseGit], хотя он может показаться слегка устаревшим.

== Документация

=== Pro Git

Пожалуй, лучший источник информации о Git – это книга "Pro Git".
Она доступна бесплатно онлайн в виде сайта и оффлайн в виде электронных и бумажных книг и переведена силами сообщества (в т.ч. и вашего покорного слуги) на многие языки мира.
Версию на русском можно найти здесь: https://git-scm.com/book/ru/v2[Pro Git 2].

В первую очередь нас будут интересовать главы:

* 1. Введение
* 2. Основы Git
* 3. Ветвление в Git

Полезными, но не столь важными для нас, будут главы:

* 5. Распределенный Git
* 6. GitHub
* 7. Инструменты Git
* 8. Настройка Git

=== Справочник Git

Книга "Pro Git" даёт отличное представление о работе с Git в целом, но не покрывает все возможные опции и параметры команд Git.
Эту информацию, в случае необходимости, можно найти в https://git-scm.com/docs[справочнике Git].
К сожалению, он не переведён на русский.

=== Шпаргалка Git

Держите под рукой: https://training.github.com/downloads/ru/github-git-cheat-sheet :)
