= Git

https://git-scm.com[Git] – это система контроля версий, используемая на подавляющем большинстве проектов в наши дни.
Знание Git (наряду с английским и навыками коммуникации) - ключ к успешной карьере инженера в IT (а не Java или фреймворки/библиотеки).

== Установка Git

Git, как и большинство инструментов разработки, доступен для Linux, Windows и macOS.
Отправная точка для установки Git – https://git-scm.com/downloads[страница "Downloads"] на официальном сайте.
Следуйте инструкциям на странице, соответствующей вашей операционной ситеме.

== Документация

=== Pro Git

Пожалуй, лучший источник информации о Git – это книга "Pro Git".
Она доступна бесплатно онлайн в виде сайта и оффлайн в виде электронных и бумажных книг и переведена силами сообщества (в т.ч. и вашего покорного слуги) на многие языки мира.
Версию на русском можно найти здесь: https://git-scm.com/book/ru/v2[Pro Git 2].

В первую очередь нас будут интересовать главы:

* 1. Введение
* 2. Основы Git
* 3. Ветвление в Git

Полезными, но не столь важными для нас, будут главы:

* 5. Распределенный Git
* 6. GitHub
* 7. Инструменты Git
* 8. Настройка Git

=== Справочник Git

Книга "Pro Git" даёт отличное представление о работе с Git в целом, но не покрывает все возможные опции и параметры команд Git.
Эту информацию, в случае необходимости, можно найти в https://git-scm.com/docs[справочнике Git].
К сожалению, он не переведён на русский.

=== Шпаргалка Git

Держите под рукой: https://training.github.com/downloads/ru/github-git-cheat-sheet :)
