= IDE

IDE — integrated development environment или eдиная среда разработки — это "блокнот" программиста.
Но не простой, а очень навороченный, сильно упрощающий жизнь этому самому программисту.
Минимальный набор возможностей (фич) IDE, которые пригодятся нам, это:

- Подсказки при написании кода.
IDE знает наш язык программирования и будет помогать писать на нём.
Также IDE "понимает" открытый в нём проект и будет подсказывать имена доступных классов, переменных, методов и прочее.
- Исправление очевидных ошибок.
IDE не позволяет писать код, который не скомпилируется (справедливо для разработки на Java).
Также IDE распознаёт опасные ситуации в коде и предупреждает программиста, часто предлагая исправления и улучшения.
- Генерация кода.
Программирование на Java включает в себя написание большого количества однообразного, шаблонного кода (boilerplate code).
IDE генерирует этот код за программиста.
- Форматирование кода.
Я не зря вынес это в отдельный пункт.
Единообразное форматирование кода всеми участниками проекта — важная составляющая процесса совместной работы над кодом.
- Рефакторинг.
Словом рефакторинг обозначают все те необходимые активности, возникающиее в процессе работы с существующим кодом: от простого переименований переменных, до глубокого изменения структуры проекта.
- Навигация по документации и исходному коду используемых библиотек.
IDE позволяет просматривать документацию на используемые библиотеки и их исходный код (при наличии обоих), не отрываясь от процесса разработки.
К сожалению, не все библиотеки имеют хорошую документацию и примеры, но большинство имеет открытый и доступный исходный код.  
- Сборка и запуск проектов.
IDE умеет компилировать и запускать ваш код, чем программисты часто пользуются на этапе разработки.
Сразу отмечу, что код, "идущий в продакшен" (финальный, окончательный, если можно так сказать, вариант кода) не собирается программистами в IDE.
Для этого используются инструменты сборки кода (о которых мы обязательно поговорим далее), часто запускаемые на отдельных серверах.
- Работа с системами контроля версий.
Некоторые программисты используют встроенные в IDE средства для работы с link:git.adoc[Git].

Это далеко не полный список возможностей совсременных IDE.
Такие фичи как учёт рабочего времени (таймтрекинг), интеграции с системами управления проектами и учёта багов (project management software / bugtrackers), плагины для баз данных, используемых на проекте, и даже просто напоминалки упражнений для глаз существенно облегчают жизнь разработчиками.

IDE — ваш бро.

== IntelliJ IDEA

Пожалуй, лучшие IDE в мире делает компания JetBrains.
Мы будем использовать их флагманский продукт — IDE для Java под названием "IntelliJ IDEA".
Она существует в платной и бесплатной версиях, для наших целей вполне хватит бесплатной.

Скачайте и установите IntelliJ IDEA Community Edition https://www.jetbrains.com/ru-ru/idea/download[со страницы загрузок].

=== Документация

==== Сайт JetBrains

Несмотря на то, что JetBrains — компания с русскими корнями, документация по их продуктам доступна только на английском языке :(
Тем не менее, вот ссылка на https://www.jetbrains.com/idea/resources[портал документации].
Здесь можно найти исчерпывающее описание всех возможностей IDEA в формате справочника или видео.

==== YouTube

Визуалы могут посмотреть https://youtu.be/yefmcX57Eyg[этот ролик].
Нельсон, автор видео, говорит на хорошем английском, медленно и разборчиво, так что я рекомендую попробовать его всем, кто знаком с английским.
В принципе, оно покрывает все необходимые нам возможности IDEA.

Я постарался записать адаптацию ролика Нельсона https://youtu.be/b1fXNLS-cyw[на русском].
Содержимое то же, качество несравнимо хуже, но общее представление о работе с IDEA вы получите.
Если не уснёте :)

==== Stepik

Забегая вперёд, порекомендую русскоязычный модуль № 1.3 из https://stepik.org/course/187[этого бесплатного курса] по Java на Stepik.
Он здорово поможет со знакомством с IDEA и выполнением некоторых пунктов link:ide_tasks.adoc[ДЗ].
