= Домашнее задание по базовому синтаксису Java

. Создайте репозиторий у себя в GitHub для этого задания.
. Создайте проект с решением одной или нескольких задачек ниже.
. Отправьте код с решениями на GitHub и поделитесь ссылкой с менторами.

== Задачки

=== Fizz Buzz

Бессмертная классика собеседований.

Напишите программу, выводящую числа от 1 до заданного N, по одному в строке.
К числам, делящимся нацело на 3, нужно дописать "Fizz".
К числам, делящимся нацело на 5, нужно дописать "Buzz".
К числам, делящимся нацело и на 3 и на 5, нужно дописать "FizzBuzz".

=== Римские числа

Римские числа записываются с помощью символов I, V, X, L, C, D и M, имеющими следующие значения:

|=== 
| I | 1
| V | 5
| X | 10
| L | 50
| C | 100
| D | 500
| M | 1000
|=== 

Например, число 2 записываетя как II (I + I), 12 — как XII (X + I + I), 27 — как XXVII (XX + V + II).
Обычно римские цифры в числе записываются от больших к меньшим, а результат получается простым сложением. 

Но есть и исключения.
4 записывается не как IIII, а как IV (V - I).
Всего есть 6 случаев (комбинаций римских цифр), когда используется вычитание вместо сложения:

|===
| IV | 4
| IX | 9
| XL | 40
| XC | 90
| CD | 400
| CM | 900
|===

Собственно, задача: считайте из консоли римское число и преобразуйте его в арабское (обычное).

=== Проверка номера банковской карты (Алгоритм Луна)

Номера банковских карт в некоторой степени защищены от ошибок передачи (например, при надиктовывании) алгоритмом Луна.
Этот алгоритм был разработан немецким компьютерным специалистом Гансом Луном в 1954-м году.
Он использует для проверки простое правило вычисления контрольной суммы.
Алгоритм определяет ошибки ввода одной неправильной цифры, а также почти все перестановки соседних цифр, за исключением перестановки 09-90 или обратной 90-09.
Полное и подробное описание можно найти, например, на https://ru.wikipedia.org/wiki/%D0%90%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC_%D0%9B%D1%83%D0%BD%D0%B0#Java[википедии].
Там же есть и реализация на Java, но в этом задании мы предлагаем вам написать свою.

Задача: считайте из консоли номер кредитки и проверьте его по алгоритму Луна.
